modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Samlegamer/heartofender/issues"

[[mods]]
modId="heartofender"
version="1.18.2-1.0"
displayName="Heart of Ender"
displayURL="https://www.curseforge.com/minecraft/mc-mods/heart-of-ender"
logoFile="banner.png"
credits=""
authors="Samlegamer"
description='''
This Mod Heart of Ender added new Blocks, Items, Food, Weapons, Mobs and Dimension !
'''

[[dependencies.heartofender]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.heartofender]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.heartofender]]
    modId = "structure_gel"
    mandatory = true
    ordering = "AFTER"
    versionRange = "NONE"

[[dependencies.heartofender]]
    modId = "quark"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"

[[dependencies.heartofender]]
    modId = "charm"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"

[[dependencies.heartofender]]
    modId = "aquaculture"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"

[[dependencies.heartofender]]
    modId = "ironchest"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"