modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="heartofender" #mandatory
version="1.18.1-1.2" #mandatory
displayName="Heart of Ender"
displayURL="https://www.curseforge.com/minecraft/mc-mods/heart-of-ender"
logoFile="banner.png" #optional
credits="" #optional
authors="Samlegamer" #optional
description='''
This Mod Heart of Ender added new Blocks, Items, Food, Weapons, Mobs and Dimension !
'''
[[dependencies.heartofender]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="AFTER"
    side="BOTH"

[[dependencies.heartofender]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.heartofender]]
    modId = "structure_gel"
    mandatory = true
    ordering = "AFTER"
    versionRange = "NONE"

[[dependencies.heartofender]]
    modId = "quark"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"

[[dependencies.heartofender]]
    modId = "charm"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"

[[dependencies.heartofender]]
    modId = "aquaculture"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"

[[dependencies.heartofender]]
    modId = "ironchest"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"